#!/usr/bin/env sh

if [ -z "$(which bb 2>/dev/null)" ]
then
    echo
    echo "Looks like you don't have babashka installed, do so with this on linux"
    echo
    echo "curl -sLO \"https://raw.githubusercontent.com/babashka/babashka/master/install\""
    echo "chmod +x install"
    echo "sudo ./install"
    echo
    echo "or on mac "
    echo
    echo "brew install borkdude/brew/babashka"
    exit 1
fi

if [ -n "$CONCIERTO_APP" ]
then
    cd $CONCIERTO_APP
else 
    CONCIERTO_APP=$(pwd)
fi

CONDIR="$CONCIERTO_APP/.concierto"
JAR="$CONDIR/concierto.jar"

case $1 in

update)
    mkdir -p $CONDIR
    tmpfile=$(mktemp)
    wget "https://www.conciert.io/release/concierto.jar" -O $tmpfile
    if [ $? -eq 0 ]
    then
        if [ -e "$JAR" ]
        then
            ver="$(bb $JAR version --tag)"
            mv $JAR "$CONDIR/concierto-$ver.jar"
        fi
        
        mv $tmpfile $JAR
    else
        echo "Didn't download concierto.jar"
    fi
;;

starter-pack)
    wget "https://www.conciert.io/release/starter-pack.tar.gz"
    if [ -e "starter-pack.tar.gz" ]
    then
        echo
        read -p "I'm going to untar the starter-pack and remove the gz is this ok (y to proceed) ? " goahead
        if [ "$goahead" = "y" ]
        then
            tar xzf starter-pack.tar.gz
            rm starter-pack.tar.gz
        fi
    fi
;;

*)
    
    if [ -n "$CONCIERTO_HOME" ];
    then
        # for dev
        bb --config $CONCIERTO_HOME/bb.edn -m concierto.cli "$@"
    else
        if [ -e "$JAR" ]
        then
            bb $JAR "$@"
        else
            echo "Concierto not initialised."
            echo "concierto.jar not found in $CONDIR, or source in CONCIERTO_HOME env."
            echo "'concierto update' to get latest jar in $CONDIR."
        fi
    fi

;;

esac