
COMMANDS
---------

scenarios       List scenarios
targets         List targets
machines        List machines
services        List services
gather          Show all defined attributes of target
ssh             Execute a command over set of machines
set             Set a variable in concierto.conf
unset           Unset a variable in concierto.conf
visit           Visit a machine by IP, specified by host, e.g. visit stage-api1
exec            Run a templated script locally
rexec           Run a templated script remotely over set of machines
template        Template a file, --in <file> --out <file>, otherwise prints to stdout
build all       Build all services listed in services/build.edn in order, --push to push
build role      Build all services referenced by role, --push to push
build           Build the service(s), --push to push
push            Push the built service to registry
deploy          Deploy over set of machines
lint            Check for inconsistencies
version         Current version, --tag show tag only

EXTENSIONS
----------

mycompany disk-size            Find disk usage for selected devices
demo lxd cluster-base-image    base Alpine with extras
demo lxd cluster-create        create a new cluster
demo lxd cluster-remove        remove cluster instance
demo lxd cluster-remove-all    remove all cluster instances
demo registry create           create a local registry

            
MACHINE SELECTION
-----------------
            
Select machines with --select <key val>* also <key val>*

e.g. concierto machines --select cluster us role api        

ENVIRONMENT VARIABLES
---------------------
            
CONCIERTO_APP    set the app directory            
CONCIERTO_SCENARIO set the scenario directory
CONCIERTO_TARGET set the target directory
            
SWITCHES
--------
            
--verbose (-v) switch on messages
--dry-run      print commands to execute
--role <role>  specify role when not included in machine selection
--json         output as json
--list         output as list
--debug        dump templated deploy into 'debug' dir

DEFAULTS
--------

The following variables may be set in config using the set command,
and are stored in  concierto.conf 

scenario    - provide a default scenario
target      - provide a default target
engine      - provide a default engine; docker or podman (default docker)
extensions  - merge extensions (default true)
remote-exec - provide a path to a file that is executed remotely on deploy                                   

e.g. concierto set scenario myscenario
                                    
For more info mail contact@conciert.io

